import * as CLS_SFX/*SUFFIX*/ from './classNameSuffix.scss'

export default {
  'simple': [
    CLS_SFX.D0, CLS_SFX.D1, CLS_SFX.D2, CLS_SFX.D3, CLS_SFX.D4,
    CLS_SFX.D5, CLS_SFX.D6, CLS_SFX.D7, CLS_SFX.D8, CLS_SFX.D9,
    CLS_SFX.POINT, CLS_SFX.SIGN, CLS_SFX.BACK, CLS_SFX.RESET,
    CLS_SFX.ADD, CLS_SFX.SUB, CLS_SFX.MUL, CLS_SFX.DIV, CLS_SFX.EVAL,
    CLS_SFX.MEM_ADD, CLS_SFX.MEM_SUB, CLS_SFX.MEM_CLEAR, CLS_SFX.MEM_RESTORE,
  ],
  'advanced': [
    CLS_SFX.D0, CLS_SFX.D1, CLS_SFX.D2, CLS_SFX.D3, CLS_SFX.D4,
    CLS_SFX.D5, CLS_SFX.D6, CLS_SFX.D7, CLS_SFX.D8, CLS_SFX.D9,
    CLS_SFX.D000, CLS_SFX.POINT, CLS_SFX.SIGN, CLS_SFX.RESET,
    CLS_SFX.ADD, CLS_SFX.SUB, CLS_SFX.MUL, CLS_SFX.DIV, CLS_SFX.EVAL,
    CLS_SFX.L_BR, CLS_SFX.R_BR, CLS_SFX.MOVE_L, CLS_SFX.MOVE_R, CLS_SFX.BACK, CLS_SFX.DEL,
    CLS_SFX.SIN, CLS_SFX.COS, CLS_SFX.TAN, CLS_SFX.ASIN, CLS_SFX.ACOS, CLS_SFX.ATAN,
    CLS_SFX.LN, CLS_SFX.LOG_Y, CLS_SFX.LOG_10, CLS_SFX.POW_Y, CLS_SFX.POW_OF_10,
    CLS_SFX.SQRT, CLS_SFX.ROOT_Y, CLS_SFX.INVERSE,
    CLS_SFX.AVG, CLS_SFX.DEG, CLS_SFX.PERCENT,CLS_SFX.COMMA,
    CLS_SFX.PI, CLS_SFX.EXP,
  ],
};
